Update README.md
ubuntu/gnome-sdk pull request #1
Opened 2022-03-31 18:11 UTC by sergiusens

2022-03-31 20:23 UTC, kenvandine commented
Actually this shows the old gitlab url

2022-05-25 12:38 UTC, jbicha commented
@sergiusens Do you want to update this pull request based on Ken's comment?

2022-05-25 17:37 UTC, sergiusens commented
Sure, I thought he went ahead and fixed it himself :sweat_smile:

2022-10-21 09:35 UTC, sergio-costas requested changes

2022-10-21 09:35 UTC, sergio-costas commented on README.md
> +git clone -b gnome-42-2204-sdk https://gitlab.gnome.org/Community/Ubuntu/gnome-sdk.git gnome-42-2204-sdk
```suggestion
git clone -b gnome-42-2204-sdk https://github.com/ubuntu/gnome-sdk.git gnome-42-2204-sdk

```

2022-10-21 10:11 UTC, merged