DT-1290: Add libva, intel-gmm and intel-media-driver
ubuntu/gnome-sdk pull request #134
Opened 2023-05-18 15:24 UTC by sergio-costas

This patch adds the libAV library with DRI3 support, the Intel Graphics Memory Manager library (needed for the driver) and the Intel Media Driver.

2023-05-18 20:21 UTC, kenvandine requested changes

2023-05-18 20:21 UTC, kenvandine commented on snapcraft.yaml
> +    after: [ libtool, meson-deps, libayatana-appindicator ]
Does libva really need to be after libayatana-appindicator?

2023-05-19 09:51 UTC, sergio-costas commented on snapcraft.yaml
> +    after: [ libtool, meson-deps, libayatana-appindicator ]
Not really... it was just to build it "in order".

2023-05-19 09:58 UTC, sergio-costas commented
Anyway, as I see, firefox still uses gnome-3-38...

2023-05-19 13:47 UTC, kenvandine approved these changes
Thanks, this is good to land

2023-05-19 13:47 UTC, merged