Fix glib-mkenums
ubuntu/gnome-sdk pull request #261
Opened 2024-11-20 14:38 UTC by sergio-costas

The 'conditioning' part is replacing '/usr/bin/python' in glib- mkenums file with '/usr/bin/python3', to ensure that it works with the current builds. Unfortunately, this only works if the original shebang was referring to python2. The current version of glib-mkenums, instead, has a shebang that already points to python3, so the result of the sed command is a shebang that points to python33, resulting in an execution error.

This patch fixes it by ensuring that the replacement is done only if the shebang points to "python", but not if it points to "python3".

Fix https://github.com/ubuntu/gnome-sdk/issues/260

2024-11-20 19:48 UTC, seb128 requested changes
Thanks. The existing code seems weird, basically it is making the interpreter be "#!python3" which isn't valid right?

Could we simply remove that sed call instead?

We know that glib is using python3 in noble and it will not go back, is there really a case where it would ever do something?

2024-11-21 08:44 UTC, sergio-costas commented
Yes, you are right. Also, I missed the fact that it removed the `/usr/bin/` part, which is completely wrong.

Done the removal. But, just in case, wait until I test it.

2024-11-21 09:46 UTC, sergio-costas commented
Confirmed: it works.

2024-11-21 09:47 UTC, seb128 approved these changes
Great, thanks!

2024-11-21 09:47 UTC, merged